// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eznoiagevruqsnrwqqwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6bm9pYWdldnJ1cXNucndxcXdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTUwMjMsImV4cCI6MjA2NTUzMTAyM30.LHDmK6vfLG1bV1wc-RNETFEyiAO_nQ1HilLGH4ty4yY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);